import{a as g,S as m,i as u}from"./assets/vendor-Dl6Guels.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h="https://pixabay.com/api/",y="50360143-67f83f4bf6f92da79a63477ea";function L(o){return g.get(h,{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data).catch(t=>{throw console.error("Axios error:",t),t})}const l=document.querySelector(".gallery"),a=document.querySelector(".loader");let n;function b(o){l.innerHTML="";const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:c,comments:p,downloads:d})=>`<li class="item-image">
        <a href="${s}">
          <img class="image" src="${i}" alt="${e}">
        </a>
        <div class="info">
          <p class="info-item"><span>Likes</span> ${r}</p>
          <p class="info-item"><span>Views</span> ${c}</p>
          <p class="info-item"><span>Comments</span> ${p}</p>
          <p class="info-item"><span>Downloads</span> ${d}</p>
        </div>
      </li>`).join(`
`);l.insertAdjacentHTML("beforeend",t),n?n.refresh():n=new m(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionsDelay:250})}function P(){l&&(l.innerHTML="",n&&(n.destroy(),n=null))}function S(){a==null||a.classList.remove("hidden")}function q(){a==null||a.classList.add("hidden")}const f=document.querySelector(".form");new m(".gallery a",{captionsData:"alt",captionDelay:250});f.addEventListener("submit",o=>{o.preventDefault(),P();const t=o.target.elements["search-text"].value.trim();if(!t){u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S(),L(t).then(i=>{const s=i.hits;if(s.length===0){u.warning({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}b(s),f.reset()}).catch(i=>{console.error("Помилка при отриманні зображень:",i.message),u.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",timeout:3e3})}).finally(()=>{q()})});
//# sourceMappingURL=index.js.map
